name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - "**.puml"

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Get changed UML files
        id: getfile
        run: |
          echo "files=$(git diff --name-only HEAD^ HEAD | grep .puml | xargs)" >> $GITHUB_OUTPUT

      - name: Generate PNG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tpng -o /github/workspace/doc/ ${{steps.getfile.outputs.files}}

      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v4.15.3
        with:
          commit_message: "Generate PNG files for PlantUML diagrams"
          branch: ${{ github.head_ref }}
